make wbStorage Little Endian, fix bug and improved test.
bittide/bittide-hardware pull request #153
Opened 2022-10-12 14:24 UTC by lmbollen

This PR fixes an addressing bug in wbStorage where wbStorage would terminate transactions with an error whenever the given address targest the upper half of its memory.
The test was adjusted to also generate inputs that should result in errors.

Furthermore the component has been changed to store data as Little Endian to conform with RISC-V.

2022-10-19 17:11 UTC, vmchale commented on bittide/src/Bittide/DoubleBufferedRam.hs
> +    -- The depth is the number of words (4 bytes), while the wishbone address addresses per byte.
> while the wishbone address addresses per byte.

I don't understand this phrase.

2022-10-21 07:58 UTC, lmbollen commented on bittide/src/Bittide/DoubleBufferedRam.hs
> +    -- The depth is the number of words (4 bytes), while the wishbone address addresses per byte.
PTAL

2022-12-12 16:19 UTC, martijnbastiaan requested changes
I don't think the title matches the content. You're only fixing the `*2` => `*4` bug and tests. The rest are cosmetic changes.

2022-12-15 13:48 UTC, martijnbastiaan approved these changes

2022-12-15 15:32 UTC, lmbollen commented on bittide/tests/Tests/DoubleBufferedRam.hs
> +      goldenInput    = fromRight RamNoOp <$> generatedInput
Indeed all illegal inputs that should lead to an error are removed from the `goldenInput`. The behavorial model only processes the legal inputs and the errors that result from the illegal inputs are afterwards added in line `724`

```Haskell
goldenTransactions = L.zipWith expectTransaction generatedInput simGolden
```

```Haskell
expectTransaction ramOp response = case ramOp of
  Right op -> ramOpToTransaction op response
  Left  op -> Just (Error (ramOpToWb op))
```

2022-12-15 16:46 UTC, merged