Improve endianness throughout designs + rxUnit refactor.
bittide/bittide-hardware pull request #158
Opened 2022-10-20 14:02 UTC by lmbollen

During the simiulation of Bittide nodes, I encountered the problem that the endianness of components was mostly big endian, while riscv uses little endian.

To fix it I changed our `RegisterBank` type to contain endianness information with a new type `ByteOrder`.

The purpose of the changes is to create clarity regarding the endianness of components (Everything accessible with Wishbone should be `LittleEndian`) and enforce the correct conversion between `RegisterBank`s and the contained data.

2022-10-21 12:11 UTC, cuddlefishie reviewed
Looks good! Some small formatting suggestions and an (for now?) unused function

2022-10-21 13:05 UTC, lmbollen commented on bittide/src/Bittide/SharedTypes.hs
> +convertLe (regBank, a) = (getDataLe regBank, getRegsLe a)
I think that indeed it's not used anywhere currently, I mostly added it for completeness. 
I'll remove it, since it's trivial to reproduce anyways.

2022-12-12 13:10 UTC, martijnbastiaan reviewed
My biggest question is: do we really want this to be configurable? RISCV is little endian, do we care about anything else?

2022-12-12 13:10 UTC, martijnbastiaan commented on bittide/src/Bittide/SharedTypes.hs
> +-- | Stores any arbitrary datatype as a vector of registers.
```suggestion
data ByteOrder = LittleEndian | BigEndian

-- | Stores any arbitrary datatype as a vector of registers.
```

2022-12-15 16:18 UTC, martijnbastiaan requested changes

2022-12-15 16:18 UTC, martijnbastiaan commented on bittide/src/Bittide/Link.hs
> +{-# OPTIONS_GHC -fconstraint-solver-iterations=0 #-}
pls no

2022-12-15 16:23 UTC, martijnbastiaan approved these changes

2022-12-15 17:52 UTC, merged