Add circuitry to extract DNA from KCU105
bittide/bittide-hardware pull request #252
Opened 2023-02-14 11:13 UTC by lmbollen

The FPGA found on the KCU105 development board features a `DNA_PORTE2` that can be used to extract a unique device identifier.

This PR adds a blackbox to instantiate `DNA_PORTE2` and control circuitry to extract this identifier.
We can use this to make a single bitstream that can be used for multiple FPGAs without address collisions.

TODO:
 - [x] Test blackbox inference in Vivado

2023-02-16 08:06 UTC, martijnbastiaan requested changes

2023-02-16 08:06 UTC, martijnbastiaan commented on bittide-extra/src/Bittide/Extra/DeviceId.hs
> +dnaPorte clk din read shift = resize <$> regOut
```suggestion
dnaPorte clk dnaSimValue din read shift = resize <$> regOut
```

2023-02-16 08:06 UTC, martijnbastiaan commented on bittide-extra/src/Bittide/Extra/DeviceId.hs
> +    (pure 0x5555555555555555)
```suggestion
    (pure dnaSimValue)
```

2023-02-16 08:06 UTC, martijnbastiaan commented on bittide-extra/src/Bittide/Extra/DeviceId.hs
> +      ((\a b -> slice d96 d1 $ pack (a, b)) <$> din <*> regOut)
```suggestion
      (+>>.) <$> din <*> regOut)
```

2023-02-16 08:06 UTC, martijnbastiaan commented on bittide-extra/src/Bittide/Extra/DeviceId.hs
> +      // Start DNA-PORTE2 instantiation
```suggestion
      // Begin DNA-PORTE2 instantiation
```

2023-02-16 08:06 UTC, martijnbastiaan commented on bittide-extra/src/Bittide/Extra/DeviceId.hs
> +      // Stop DNA-PORTE2 instantiation
```suggestion
      // End DNA-PORTE2 instantiation
```

For consistency with `clash-lib`.

2023-02-16 08:06 UTC, martijnbastiaan commented on bittide-extra/src/Bittide/Extra/DeviceId.hs
> +    newShift = input ++# slice d95 d1 reg
```suggestion
    input +>>. reg
```

2023-02-17 10:21 UTC, lmbollen commented on bittide-extra/src/Bittide/Extra/DeviceId.hs
> +  | DONE
Nope

2023-05-09 09:09 UTC, martijnbastiaan approved these changes
LGTM, I'll move it to `clash-cores`.

2024-02-08 12:50 UTC, merged