use a custom program streaming format
bittide/bittide-hardware pull request #300
Opened 2023-05-16 13:07 UTC by cuddlefishie

As part of #291 , this format will reduce the amount of data that needs to be transferred to a bootloader, making iteration times shorter.

TODOs:
- [ ] write tests

2023-05-24 12:41 UTC, martijnbastiaan requested changes
Could you:

 * Add Haddock documentation to your Haskell functions
 * Write a PR cover letter: it should answer the question why this reduce the amount of memory we need to transfer binaries

But as far as I can tell: looks good!

2023-05-24 12:41 UTC, martijnbastiaan commented on bittide/src/Bittide/ProcessingElement/ProgramStream.hs
> +    Address
```suggestion
    , elfStreamStructure
    , elfStream
    . ZeroPaddingLength
    , IsExecutable
    , Segment
    , Address
```

2023-05-24 12:41 UTC, martijnbastiaan commented on bittide/src/Bittide/ProcessingElement/ProgramStream.hs
> +      in segEntry : acc
Deduplicate this with a `goSegment`?

2023-05-24 12:41 UTC, martijnbastiaan commented on firmware/bittide-sys/tests/program_stream.rs
> +unsafe fn write_program_to_memory(input: &mut impl Iterator<Item = u8>) -> Option<()> {
This seems to always return a trivial `Some()`. What's up with this return type? Shouldn't it return simply nothing?

2023-05-24 14:03 UTC, martijnbastiaan commented on firmware/bittide-sys/tests/program_stream.rs
> +unsafe fn write_program_to_memory(input: &mut impl Iterator<Item = u8>) -> Option<()> {
Great makes sense

2023-05-25 11:00 UTC, cuddlefishie commented
Added haddock comments, a new property test to make sure the streaming format will always be smaller than an ELF (just a sanity check) and the PR description was updated!

2023-05-31 18:47 UTC, martijnbastiaan approved these changes

2023-06-01 08:40 UTC, merged