Add pre-process step and a driver function to the test infrastructure
bittide/bittide-hardware pull request #664
Opened 2024-10-30 16:04 UTC by hydrolarus

WIP, just putting everything here, not done yet updating the existing tests

2024-11-06 15:40 UTC, hydrolarus commented on bittide-shake/exe/Main.hs
> +  callProcess "cabal" ["run", preProcessMain]
Oops I think this can be removed

2024-11-11 10:29 UTC, hydrolarus commented
Since this rewrites all the tests using VexRiscv to be programmed before HITL test start it needs to access all FPGAs via JTAG, but #649 blocks this, so the software clock control HITL test is blocked on that.

2024-11-18 08:17 UTC, hiddemoll commented
PR #649 has been closed in favor of #675 , which has been merged last Friday.

2024-11-27 15:49 UTC, martijnbastiaan requested changes
Very nice!

My biggest concern is use of manual cleanup calls. We should make sure we clean up properly, even in case of errors --- hence the need for bracket style resource allocation. Other than that LGTM.

2024-11-27 15:49 UTC, martijnbastiaan commented on vivado-hs/src/Vivado/Tcl.hs
> +openHwT v hwT = do
```suggestion
openHwTarget :: VivadoHandle -> HwTarget -> IO ()
openHwTarget v hwT = do
```

2024-12-03 12:26 UTC, hydrolarus commented on bittide-instances/src/Bittide/Instances/Hitl/Driver/VexRiscv.hs
> +  (ocd, ocdClean) <- startOpenOcd deviceInfo.usbAdapterLocation gdbPort
Yes, I agree generally. Here the "issue" is that the pre-process step might want to open some programs and then make them available in the driver function. If a bracket-style function is used to start programs then there's no way to pass them through to the driver function (for example opening GDB to program the core, then later interacting with it using GDB commands)

2024-12-03 12:32 UTC, hydrolarus commented on bittide-experiments/src/Bittide/Hitl.hs
> +      (VivadoHandle -> FilePath -> HwTarget -> DeviceInfo -> IO (TestStepResult c))
This does an override, an additional step would have a different signature and be more complex (how does the driver receive the user-data from multiple different pre-process functions?).

I'll add that to the docs!

2024-12-04 08:39 UTC, martijnbastiaan commented on bittide-instances/src/Bittide/Instances/Hitl/Driver/VexRiscv.hs
> +  (ocd, ocdClean) <- startOpenOcd deviceInfo.usbAdapterLocation gdbPort
Ahhh... okay I don't have a great solution right now, but be should definitely make an issue out of it.

2024-12-04 08:40 UTC, martijnbastiaan approved these changes
Let's make an issue out of resource allocation. Other than the small comments, LGTM. Can we help debugging the failing CI?

2025-01-09 13:56 UTC, martijnbastiaan approved these changes
It's a big one, so I've probably missed some things, but overall LGTM!

2025-01-09 13:56 UTC, martijnbastiaan commented on bittide-instances/src/Bittide/Instances/Hitl/Driver/SwCcTopologies.hs
> +          return (count, code)
```suggestion
      case code of
        ExitSuccess -> do
          putStrLn $ "Test succeeded on target " <> show d.deviceId
          return (count + 1, acc)
        ExitFailure n -> do
          putStrLn $ "Test failed on target " <> show d.deviceId <> " with exit code " <> show n
          return (count, code)
```

Generally, `case` statements are preferred over `if`s as they benefit from "incomplete pattern match" warnings.

2025-01-09 13:56 UTC, martijnbastiaan commented on bittide-instances/src/Bittide/Instances/Hitl/Driver/SwCcTopologies.hs
> +        <> " targets."
```suggestion
      putStrLn [i|Test case #{testName} passed on #{count} of #{L.length targets} targets|]
```

Make sure to enable ` QuasiQuotes`.

2025-01-09 13:56 UTC, martijnbastiaan commented on bittide/src/Bittide/ClockControl/CallistoSw.hs
> +  --     ((), (pure (), pure ()))
If you want to keep this comment around: comment why. Otherwise, remove.

2025-01-09 13:57 UTC, martijnbastiaan commented on bittide-instances/src/Bittide/Instances/Hitl/Driver/VexRiscv.hs
> +  (ocd, ocdClean) <- startOpenOcd deviceInfo.usbAdapterLocation gdbPort
We've since switched back to brackets!

2025-01-10 09:56 UTC, hiddemoll reviewed
Should start test probes be deasserted at the end of a test? Right now, I'm not sure if we do so for each test. Could you check if all tests have the same end-of-test behaviour regarding the start test probe values?

2025-01-10 09:56 UTC, hiddemoll commented on bittide-instances/src/Bittide/Instances/Hitl/Driver/SwCcTopologies.hs
> +      execCmd_ v "set_property" ["OUTPUT_VALUE", "1", getProbeTestStartTcl]
This doesn't look like a deasserted start probe. Shouldn't it be:
```suggestion
      execCmd_ v "set_property" ["OUTPUT_VALUE", "0", getProbeTestStartTcl]
```

2025-01-10 10:39 UTC, rslawson commented on bittide-instances/src/Bittide/Instances/Hitl/Driver/SwCcTopologies.hs
> +          return (count, code)
This is a bit of accidental left-overs from previous error reporting. I moved the failure type printing up to the `getTestResults` function instead, so I'll clean this up and remove the prints from here.

2025-01-10 10:41 UTC, rslawson commented on bittide-instances/src/Bittide/Instances/Hitl/Driver/DnaOverSerial.hs
> +  -- make sure PicoCom is started properly
It is, though I'll have to do some other cleanup too since I just noticed this isn't in bracket style either.

2025-01-10 10:42 UTC, rslawson commented on bittide-experiments/src/Bittide/Hitl.hs
> +    -- ^ Optional function driving the test after pre-processing.
As it turns out, no, the driver function must handle asserting the start probes for the devices it's being run on.

2025-01-10 10:42 UTC, rslawson commented on bittide-experiments/src/Bittide/Hitl.hs
> +    -- ^ Optional post processing step.
Yes, it's run after that and after collecting ILA data.

2025-01-10 10:51 UTC, rslawson commented on bittide-instances/src/Bittide/Instances/Hitl/Driver/SwCcTopologies.hs
> +      execCmd_ v "set_property" ["OUTPUT_VALUE", "1", getProbeTestStartTcl]
Yep, it should be. I think I copied from an earlier section and forgot to change the 1 to a 0. Thanks for catching that (:

2025-01-10 17:55 UTC, merged